### ISSUE TITLE
1.0.0 Snapshot ODFDOM Java Heap Space Error

### ISSUE THREAD

**Issue by 0x000eHx** [tdf/odftoolkit#22]
Hey there,
till now I did work with the odftoolkit version 0.9.
I did compare columns of two big ODF Spreadsheet Files (.ods) with macros and a lot of other settings.
Now I wanted to update to the odftoolkit verison 1.0.0 snapshot while using the latest Java 12 (12.0.2) and get a special Error, while using the org.odftoolkit.odfdom.doc.* namespace classes.
In verison 0.9 there were no errors with the org.odftoolkit.simple.SpreadsheetDocument etc classes.

I didn't get the right clue from the IntelliJ Debugger or I don't know all capibilities yet.
The error stack trace states a heap size problem:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.cacheTableOperation(ChangesFileSaxHandler.java:2239)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.cacheOperation(ChangesFileSaxHandler.java:2218)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.endElement(ChangesFileSaxHandler.java:1722)
	at org.odftoolkit.odfdom.pkg.rdfa.MultiContentHandler.endElement(MultiContentHandler.java:90)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:236)
	at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:70)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:105)
	at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:59)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:412)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getTables(OdfSchemaDocument.java:640)
	at org.odftoolkit.odfdom.doc.OdfDocument.getTableList(OdfDocument.java:737)
	at Comparison.<init>(Comparison.java:43)
	at Main.main(Main.java:6)
```
I did increase it till `-Xms1024m -Xmx8000m` in the project VM Options, but this just fills my memory more and won't help.

My steps so far:
After I cloned your 1.0.0_SNAPSHOT inside IntelliJ and build the .jars with the Maven Options 'install -DskipTests' I did only insert 'odfdom-java-1.0.0-SNAPSHOT-jar-with-dependencies.jar' as a project dependency.
Thats it. Is there something missing? It's not missing any classes, so I can't suggest anything.

I found out while stepping through the code, that inside the method 'initialize(DefaultHandler handler, OdfFileDom dom)' in 'OdfFileDom.java' it triggers the methode 'xmlReader.parse(xmlSource)' and after this invocation, my memory gets filled up till break down.
But stepping inside this .parse methode shows some decompiled xerces source files for which IntelliJ states, that they don't match the java bytecode. It won't help when I insert the Xerces_2.12.0 source files as project dependencies so I cant really look very deep into the problem.

=========================================================
As comparison I did write a very small program with the code which gets invoked till it breaks down.
To proof anything I created two new Spreadsheet Documents with only one table and a little content inside each.
With these sheets my small program doesn't have any problem to give out the tables. getTableList() is working as expected.
Sorry, I can't paste the big Spreadsheet Documents here, cause they contain sensible data.

Can someone give me any hints?
I hope I didn't produce a unique error there...

I'll stay with my 0.9 builds, till that issue is solved. I can't build working jar files from the odftoolkit master branch here at the moment :roll_eyes: 

Thanks in advance
eHx

EDIT:
With xerces-j in the dependencies before odftoolkit it goes deeper into the java libs:
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.LinkedList.addAll(LinkedList.java:428)
	at java.base/java.util.LinkedList.addAll(LinkedList.java:391)
	at java.base/java.util.LinkedList.<init>(LinkedList.java:123)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.cacheTableOperation(ChangesFileSaxHandler.java:2239)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.cacheOperation(ChangesFileSaxHandler.java:2218)
	at org.odftoolkit.odfdom.changes.ChangesFileSaxHandler.endElement(ChangesFileSaxHandler.java:1722)
	at org.odftoolkit.odfdom.pkg.rdfa.MultiContentHandler.endElement(MultiContentHandler.java:90)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:236)
	at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:70)
	at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:105)
	at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:59)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:412)
	at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getTables(OdfSchemaDocument.java:640)
	at org.odftoolkit.odfdom.doc.OdfDocument.getTableList(OdfDocument.java:737)
	at example.simple.Comparing.showavailableTables(Main.java:52)
	at example.simple.Main.main(Main.java:20)
```

_Originally posted by @0x000eHx in https://github.com/tdf/odftoolkit/issues/13#issuecomment-532198250_

**Comment by svanteschubert** [comment]
Closing the issue, as it was fixed as discussed in the comments!
